### ISSUE TITLE
Error in https://expo.io/@community/playlist

### ISSUE THREAD

**Issue by MedinaGitHub** [expo/playlist-example#12] opened 2017-11-30 18:00 UTC
Error while loading in Iphone 6S

**Comment by thekyriarchy** [comment] 2018-04-27 15:02
I came here to post the same thing. 

Same issue as https://github.com/expo/audio-recording-example/issues/8

**Comment by jimmylee** [comment] 2018-05-08 01:27
https://github.com/expo/expo-docs/issues/291

Closing this issue because its a duplicate of #291, I'm currently looking for examples to replace it with. If you folks have any examples I'd love to use them in our docs.

**Closed by jimmylee** 2018-05-08 01:27 UTC
